# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac4c929f897a273f95dc7079d749c35cd6ce552f358fb4b7a7c0134593ba1cdf36972fa9ecec5aba8da56bca0da6c4a2c450306b361c539a601525e7e611b4cd

test:
  secret_key_base: 6ef3f8afabd17c863f506b9fe4c9fbc68f3deb30ff8aea9eac8f81d8512c524d7b7bffbec1e9d981a2090b912a1f005cf3e09a80fe468c6bea002569de9147f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
